version: '3.8'

services:
  frontend:
    build: .
    container_name: react_frontend_aprendiz
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules # Evita que el volumen local sobrescriba los modulos del contenedor